version: "3.7"
services:
  ui:
    build: Group10.UI/
    networks:
      - Group10Network
    ports:
      - "3000:3000"
    env_file:
      - ui_env.env
  api:
    build: .
    networks:
      - Group10Network
    ports:
      - "5000:5000"
    env_file:
      - api_env.env

networks:
  Group10Network:
